version: "3"

services:
  site:
    image: jekyll/jekyll
    volumes:
      - ./:/srv/jekyll/
    environment:
      - JEKYLL_VERSION=3.8
    ports:
      - 4000:4000
    command: >
        jekyll serve